//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//
// BufferBlockAccessor.hpp
// Interface for simplified access to Dante buffers
//

#pragma once

#include "dante/BufferView.hpp"

namespace Dante {

//==========================================================
// Sample format (read/write) functions for convenience
//==========================================================

/// @brief Convert little-endian byte array to int32_t right padded proportionally (i.e. 16 bit to upper 16 bits of
/// int32_t). For use with writeTxFrames
/// @param src Little-endian source byte array
/// @param bytesPerSample Size of source sample in bytes
/// @return Resulting int32_t sample
inline int32_t littleEndianToInt32(const uint8_t * src, unsigned bytesPerSample)
{
	// Use uint32_t for bit manipulation
	uint32_t val = 0;
	// Duff's device for little endian integer format conversion to 32 bit
	switch (bytesPerSample)
	{
	case 4:
		val |= (uint32_t)(*src++) << 0;
		// fallthrough
	case 3:
		val |= (uint32_t)(*src++) << 8;
		// fallthrough
	default: // We support a minimum of 16 bits
		val |= (uint32_t)(*src++) << 16;
		val |= (uint32_t)(*src) << 24;
		break;
	}
	int32_t rval = 0;
	std::memcpy(&rval, &val, sizeof(int32_t));
	return rval;
}

/// @brief Convert int32_t sample to little-endian byte array truncating least significant bytes as needed. For use with
/// readRxFrames
/// @param dst Destination little-endian byte array
/// @param sample Source int32_t sample
/// @param bytesPerSample Size of destination sample in bytes
inline void int32ToLittleEndian(uint8_t * dst, int32_t sample, unsigned bytesPerSample)
{
	// Convert int32_t to uint32_t for bit manipulation
	uint32_t val = 0;
	std::memcpy(&val, &sample, sizeof(int32_t));
	// Duff's device for little endian integer format conversion from 32 bit
	switch (bytesPerSample)
	{
	case 4:
		*dst++ = (val >> 0) & 0xff;
		// fallthrough
	case 3:
		*dst++ = (val >> 8) & 0xff;
		// fallthrough
	default: // Minimum 16 bits
		*dst++ = (val >> 16) & 0xff;
		*dst = (val >> 24) & 0xff;
		break;
	}
}

/// @brief Convert native endianness byte array to int32_t. For use with writeTxFrames
/// @param src uint8_t pointer
/// @return Resulting int32_t sample
inline int32_t nativeInt32ToInt32(const uint8_t * src)
{
	int32_t rval = 0;
	std::memcpy(&rval, src, sizeof(int32_t));
	return rval;
}

/// @brief Convert int32_t sample to native endianness byte array. FOr use with readRxFrames
/// @param dst Destination pointer to write int32_t to
/// @param sample Source int32_t sample
inline void int32ToNativeInt32(uint8_t * dst, int32_t sample)
{
	std::memcpy(dst, &sample, sizeof(int32_t));
}

//==========================================================
// BufferBlockAccessor class and related types
//==========================================================

/// @brief Description of a contiguous block of channels in the Dante buffers
struct ChannelBlockDescription
{
	unsigned mFirstChannel;
	unsigned mNumChannels;
};

struct BlockAccessorConfig
{
	/// @brief How far ahead in time to write TX audio relative to the Dante head, in microseconds. This should be large enough
	/// to account for signal latency, scheduling jitter, the time to process a batch of samples and the length of that
	/// batch of samples. If samples to write surpasses this, then updateAvailable will report how many frames late the client is.
	/// @note Rounds down to the nearest sample.
	unsigned mTxLatencyUs = 10000;
	/// @brief For backward compatibility, the TX latency can be specified in samples instead of time. This makes it
	/// independent of the sample rate. If mTxLatencySamples > 0, it overrides mTxLatencyUs.
	unsigned mTxLatencySamples = 0;

	BlockAccessorConfig() = default;
	BlockAccessorConfig(unsigned txLatencyUs)
		: mTxLatencyUs(txLatencyUs)
	{}
};

/// @brief Manages a TX and an RX head for a block of Dante channels, and provides block copy operations for
/// reading/writing samples
class BufferBlockAccessor
{
public:
	BufferBlockAccessor(BufferView & bufferView, const BlockAccessorConfig & config);
	~BufferBlockAccessor() = default;

	/// @brief Set the channels to read/write for this block accessor. Block accessor will only update available for a
	/// direction if there are channels configured in that direction. Maintains current available counts
	/// @note If the BufferView is not in READY state, channels cannot be set, as buffer geometry is not finalised.
	/// @param txChannels Description of a contiguous block of TX channels to write to.
	/// @param rxChannels Description of a contiguous block of RX channels to read from.
	void setChannels(const ChannelBlockDescription & txChannels, const ChannelBlockDescription & rxChannels);

	/// @brief Sets the channels to read/write to all the channels available in the BufferView in each direction.
	/// @note If the BufferView is not in READY state, channels cannot be set, as buffer geometry is not finalised.
	/// @param symmetric Sets the channel counts so that RX and TX blocks have the same number of channels, being the minimum
	/// count between the RX and TX channels.
	void setChannels(bool symmetric=false);

	/// @return How many TX frames must be written now to maintain the configured TxLatency.
	/// @note This can be negative, in which case the client has written more data than strictly necessary, but there is
	/// nothing wrong with this.
	int getTxFramesToWrite() const { return mTxFramesToWrite; };

	/// @return Number of RX frames written to the Dante buffers and available to read
	unsigned getAvailRxFrames() const { return mRxAvailable; };

	/// @brief Drop some TX frames, effectively writing zeroes. framesToDrop must not be more than the total number of
	/// frames in the Dante buffer.
	/// @return The number of frames dropped
	unsigned fastForwardTx(unsigned framesToDrop)
	{
		framesToDrop = clampTxFramesToTransfer(framesToDrop);
		mClientTxHead = mBufferView.progressHead(mClientTxHead, framesToDrop);
		mTxFramesToWrite -= framesToDrop;
		return framesToDrop;
	}

	/// @brief Drop some available RX frames
	/// @return The number of frames dropped
	unsigned fastForwardRx(unsigned framesToDrop)
	{
		if (framesToDrop > mRxAvailable)
		{
			framesToDrop = mRxAvailable;
		}
		mClientRxHead = mBufferView.progressHead(mClientRxHead, framesToDrop);
		mRxAvailable -= framesToDrop;
		return framesToDrop;
	}

	/// @brief Update the available frame counts based on latest Dante update info. If there is a large stall, it will discard all available frames and reset the client heads.
	/// @param info The PollInfo from BufferView::poll()
	/// @return Returns 0 if timing is okay. If the TX head has fallen behind the Dante head, returns how late the TX head is in frames.
	/// If either head has fallen _extremely_ far behind the Dante head (i.e. more than a whole buffer size), returns -1 and resets both heads.
	int updateAvailable(const BufferView::PollInfo & info);

	/// @brief Copy audio data from client buffers to Dante TX buffers, consuming TX available frames.
	/// @param clientBuffers A vector of buffer descriptions for the client buffers
	/// using WriteSampleFn = std::function<int32_t(uint8_t * src)>;
	/// @param conversionFn Function to convert client buffer sample to Dante sample format
	/// @param clientHead (zero based) index of first frame to transfer in the client buffer
	/// @param framesToTransfer Number of frames to transfer
	/// @return Number of frames actually transferred
	template <typename WriteSampleFn>
	unsigned writeTxFrames(
		const std::vector<BufferDescription> & clientBuffers,
		WriteSampleFn conversionFn,
		unsigned clientHead,
		unsigned framesToTransfer);

	/// @brief Copy audio data from Dante RX buffers to client buffers, consuming RX available frames.
	/// @param clientBuffers A vector of buffer descriptions for the client buffers
	/// using ReadSampleFn = std::function<void(uint8_t * dst, int32_t sample)>;
	/// @param conversionFn Function to write the given Dante sample to the client buffer
	/// @param clientHead (zero based) index of first frame to transfer in the client buffer
	/// @param framesToTransfer Number of frames to transfer
	/// @return Number of frames actually transferred
	template <typename ReadSampleFn>
	unsigned readRxFrames(
		const std::vector<BufferDescription> & clientBuffers,
		ReadSampleFn conversionFn,
		unsigned clientHead,
		unsigned framesToTransfer);

	/// @brief A callback that is given a window into the Dante buffers
	/// @param numSamples The number of samples to read/write from the Dante buffer
	/// @param channelPointers Vector of pointers to the next available sample in each channel's buffer. If a channel in
	/// the configured block does not exist in the buffers, the corresponding pointer will be null.
	/// @return The number of samples actually read/written. Return 0 to indicate no more samples can be processed.
	/// using BlockAccessFn = std::function<unsigned(unsigned numSamples, std::vector<int32_t *> channelPointers)>;

	/// @brief Uses given callback to write audio to the TX buffers, consuming TX available frames.
	/// @param blockAccessFn Function to write audio to the TX buffers. May be called multiple times with
	/// 				numSamples < framesToTransfer.
	/// @param framesToTransfer The total number of frames to transfer. blockAccessFn will be called until this many
	/// 				samples are transferred, the accessor runs out of available samples or blockAccessFn returns 0.
	/// @return The actual number of frames transferred
	template <typename BlockAccessFn>
	unsigned accessTxBlock(const BlockAccessFn & blockAccessFn, unsigned framesToTransfer);

	/// @brief Uses given callback to read audio from the RX buffers, consuming RX available frames.
	/// @param blockAccessFn Function to read audio from the RX buffers. May be called multiple times with
	/// 			numSamples < framesToTransfer.
	/// @param framesToTransfer The total number of frames to transfer. blockAccessFn will be called until this many
	/// 			samples are transferred, the accessor runs out of available samples or blockAccessFn returns 0.
	/// @return The actual number of frames transferred
	template <typename BlockAccessFn>
	unsigned accessRxBlock(const BlockAccessFn & blockAccessFn, unsigned framesToTransfer);

	/// @brief Reset the client heads to the current Dante head position, discarding available RX frames and TX frames to write.
	void resetClientHeads();

private:
	void reset(unsigned sampleRate);

	unsigned clampTxFramesToTransfer(unsigned framesToTransfer) const;

	void resetTxClientHead();
	void resetRxClientHead();

	BufferView & mBufferView;

	// Config
	const unsigned mTxLatencyUs;
	const unsigned mConfiguredTxLatencySamples;

	// Which channels this block accessor reads/writes from/to.
	ChannelBlockDescription mTxChannels = {0, 0};
	ChannelBlockDescription mRxChannels = {0, 0};

	// The next frame index to read/write
	unsigned mClientTxHead = 0;
	unsigned mClientRxHead = 0;

	// How many frames must be written to maintain the configured TX latency.
	// Viewing the Dante head as virtually being at "Dante time now" + mTxLatencyUs, this is how far behind that virtual
	// head the client TX head is. This can be negative, in which case the client has written more data than strictly
	// necessary, but there is nothing wrong with this.
	int mTxFramesToWrite = 0;

	// How far the Dante head has progressed ahead of the client RX head. i.e. how many frames the client can read from
	// the RX buffers.
	unsigned mRxAvailable = 0;

	// Dynamic latency in frames based on current samplerate
	unsigned mTxLatencyFrames = 0;
};

inline BufferBlockAccessor::BufferBlockAccessor(BufferView & bufferView, const BlockAccessorConfig & config)
	: mBufferView(bufferView),
	  mTxLatencyUs(config.mTxLatencyUs),
	  mConfiguredTxLatencySamples(config.mTxLatencySamples)
{
	// If the buffers are already connected, we can initialize the view immediately. Otherwise we'll wait for the first
	// poll to do it.
	if (mBufferView.getState() == BufferView::State::READY)
	{
		reset(mBufferView.getCurrentSamplerate());
	}
}

inline void BufferBlockAccessor::setChannels(const ChannelBlockDescription & txChannels, const ChannelBlockDescription & rxChannels)
{
	if (mBufferView.getState() != BufferView::State::READY)
	{
		throw std::runtime_error("Cannot set channels until BufferView is READY");
	}
	if (txChannels.mNumChannels > 0)
	{
		if (txChannels.mFirstChannel + txChannels.mNumChannels > mBufferView.getTxChannelCount())
		{
			throw std::out_of_range("TX channel block is out of range of available TX channels");
		}
	}
	if (rxChannels.mNumChannels > 0)
	{
		if (rxChannels.mFirstChannel + rxChannels.mNumChannels > mBufferView.getRxChannelCount())
		{
			throw std::out_of_range("RX channel block is out of range of available RX channels");
		}
	}
	// Set initial head positions if it was not already set
	if (mTxChannels.mNumChannels == 0 && txChannels.mNumChannels > 0)
	{
		resetTxClientHead();
	}
	if (mRxChannels.mNumChannels == 0 && rxChannels.mNumChannels > 0)
	{
		resetRxClientHead();
	}
	mTxChannels = txChannels;
	mRxChannels = rxChannels;

	// If there are no channels in a direction, stop tracking available and client head
	if (mTxChannels.mNumChannels == 0)
	{
		mTxFramesToWrite = 0;
	}
	if (mRxChannels.mNumChannels == 0)
	{
		mRxAvailable = 0;
	}
}

inline void BufferBlockAccessor::setChannels(bool symmetric)
{
	if (mBufferView.getState() != BufferView::State::READY)
	{
		throw std::runtime_error("Cannot set channels until BufferView is READY");
	}
	unsigned numTxChannels = mBufferView.getTxChannelCount();
	unsigned numRxChannels = mBufferView.getRxChannelCount();
	if (symmetric)
	{
		// Determine the minimum number of channels between RX and TX.
		if (numTxChannels < numRxChannels)
		{
			numRxChannels = numTxChannels;
		}
		else if (numRxChannels < numTxChannels)
		{
			numTxChannels = numRxChannels;
		}
	}
	setChannels({0, numTxChannels}, {0, numRxChannels});
}

inline int BufferBlockAccessor::updateAvailable(const BufferView::PollInfo & pollInfo)
{
	if (pollInfo.mState != BufferView::State::READY)
	{
		mTxFramesToWrite = 0;
		mRxAvailable = 0;
		return 0;
	}

	if (pollInfo.mReset)
	{
		reset(pollInfo.mSamplerate);
		return 0;
	}

	// Check for extreme stalls, and in that case just reset everything
	if (pollInfo.mSamplesSinceLastUpdate >= mBufferView.getBufferSizeFrames())
	{
		resetClientHeads();
		return -1;
	}

	unsigned lateFrames = 0;
	// Update tx frames to write
	if (mTxChannels.mNumChannels > 0)
	{
		mTxFramesToWrite += static_cast<int>(pollInfo.mSamplesSinceLastUpdate);
		if (mTxFramesToWrite > static_cast<int>(mTxLatencyFrames))
		{
			// TX underrun. Dante head has definitely reached or passed client head.
			// Report how many frames late we are.
			lateFrames = static_cast<unsigned>(mTxFramesToWrite) - mTxLatencyFrames;
			if (lateFrames > mBufferView.getBufferSizeFrames())
			{
				// If we're more than a whole buffer late, just reset the heads.
				resetClientHeads();
				return -1;
			}
		}
	}

	// Update rx available
	if (mRxChannels.mNumChannels > 0)
	{
		mRxAvailable += pollInfo.mSamplesSinceLastUpdate;
		if (mRxAvailable > mBufferView.getBufferSizeFrames())
		{
			resetClientHeads();
			return -1;
		}
	}
	return lateFrames;
}

inline void BufferBlockAccessor::resetTxClientHead()
{
	// We initially set the TX head "Tx Latency" ahead of the Dante head, and we recommend you catch up every iteration.
	mClientTxHead = mBufferView.calcHeadPosition(
		mBufferView.getLatestSampleTimestamp(),
		mTxLatencyFrames);
	mTxFramesToWrite = 0;
}

inline void BufferBlockAccessor::resetRxClientHead()
{
	// The RX head starts just at current time, since we want to read the latest available samples
	mClientRxHead = mBufferView.calcHeadPosition(mBufferView.getLatestSampleTimestamp(), 0);
	mRxAvailable = 0;
}

inline void BufferBlockAccessor::resetClientHeads()
{
	if (mTxChannels.mNumChannels > 0)
	{
		resetTxClientHead();
	}
	if (mRxChannels.mNumChannels > 0)
	{
		resetRxClientHead();
	}
}

inline void BufferBlockAccessor::reset(unsigned sampleRate)
{
	mTxFramesToWrite = 0;
	mRxAvailable = 0;

	if (mConfiguredTxLatencySamples > 0)
	{
		mTxLatencyFrames = mConfiguredTxLatencySamples;
	}
	else
	{
		mTxLatencyFrames = static_cast<unsigned>((static_cast<uint64_t>(mTxLatencyUs) * sampleRate) / 1000000);
	}
	resetClientHeads();
}


inline unsigned BufferBlockAccessor::clampTxFramesToTransfer(unsigned framesToTransfer) const
{
	// The client is allowed to write beyond the "must write" point, but if they write very far beyond, they wrap
	// around to the point the Dante head is reading. So prevent writing up to that point. We add an extra period
	// of headroom in case the Dante TX head is not exactly at the reported point.
	unsigned maxFramesBuffered = mBufferView.getBufferSizeFrames() - mTxLatencyFrames - mBufferView.getPeriodSizeFrames();

	// How far beyond the "must write" point TX audio would buffered after this transfer
	// Note that if mTxFramesToWrite > framesToTransfer this is negative
	int framesBufferedAfterTransfer = static_cast<int>(framesToTransfer) - mTxFramesToWrite;

	if (framesBufferedAfterTransfer > static_cast<int>(maxFramesBuffered))
	{
		unsigned overrunFrames = static_cast<unsigned>(framesBufferedAfterTransfer) - maxFramesBuffered;
		framesToTransfer -= overrunFrames;
	}
	return framesToTransfer;
}

template <typename WriteSampleFn>
inline unsigned BufferBlockAccessor::writeTxFrames(
	const std::vector<BufferDescription> & clientBuffers,
	WriteSampleFn convertFn, // std::function<int32_t(uint8_t *)>
	unsigned clientBufHead,
	unsigned framesToTransfer)
{
	const unsigned numChannels = mTxChannels.mNumChannels;
	if (clientBuffers.size() != numChannels)
	{
		throw std::invalid_argument("Number of client buffers does not match configured TX channel block size");
	}

	if (numChannels == 0)
	{
		throw std::invalid_argument("No TX channels configured");
	}

	if (clientBufHead >= clientBuffers[0].mBufferSizeFrames)
	{
		throw std::invalid_argument("Invalid head index for client buffer size");
	}

	framesToTransfer = clampTxFramesToTransfer(framesToTransfer);

	// Transfer the samples
	for (unsigned channel = 0; channel < numChannels; ++channel)
	{
		const BufferDescription & clientBufRef = clientBuffers[channel];
		// Temporary heads for this channel
		uint8_t * clientBufferLastPtr = clientBufRef.sampleAt(clientBufRef.mBufferSizeFrames - 1);
		uint8_t * clientBufferHeadPtr = clientBufRef.sampleAt(clientBufHead);
		unsigned danteBufferHead = mClientTxHead;
		for (unsigned sample = 0; sample < framesToTransfer; sample++)
		{
			// Copy the sample
			int32_t danteSample = convertFn(clientBufferHeadPtr);
			mBufferView.setTxSample(mTxChannels.mFirstChannel + channel, danteBufferHead, danteSample);

			// Advance temporary heads
			if (clientBufferHeadPtr == clientBufferLastPtr)
			{
				clientBufferHeadPtr = clientBufRef.sampleAt(0);
			}
			else
			{
				clientBufferHeadPtr += clientBufRef.mStrideBytes;
			}
			danteBufferHead = mBufferView.progressHead(danteBufferHead, 1);
		}
	}

	// Finally advance the shared head and the available count
	mClientTxHead = mBufferView.progressHead(mClientTxHead, framesToTransfer);
	mTxFramesToWrite -= static_cast<int>(framesToTransfer);
	return framesToTransfer;
}

template <typename ReadSampleFn>
inline unsigned BufferBlockAccessor::readRxFrames(
	const std::vector<BufferDescription> & clientBuffers,
	ReadSampleFn convertFn, // std::function<void(uint8_t *, int32_t)>
	unsigned clientBufHead,
	unsigned framesToTransfer)
{
	const unsigned numChannels = mRxChannels.mNumChannels;

	if (clientBuffers.size() != numChannels)
	{
		throw std::invalid_argument("Number of client buffers does not match configured RX channel block size");
	}

	if (numChannels == 0)
	{
		throw std::invalid_argument("No RX channels configured");
	}

	if (clientBufHead >= clientBuffers[0].mBufferSizeFrames)
	{
		throw std::invalid_argument("Invalid head index for client buffer size");
	}

	// If we read beyond the Rx available, we get into the realm of data which the
	// DEP does not guarantee to be written yet. (In practice it usually is, but
	// this is dependent on the headroom between the configured and actual Rx latency).
	if (framesToTransfer > mRxAvailable)
	{
		framesToTransfer = mRxAvailable;
	}

	// Transfer the samples
	for (unsigned channel = 0; channel < numChannels; ++channel)
	{
		const BufferDescription & clientBufRef = clientBuffers[channel];
		// Temporary heads for this channel
		uint8_t * clientBufferLastPtr = clientBufRef.sampleAt(clientBufRef.mBufferSizeFrames - 1);
		uint8_t * clientBufferHeadPtr = clientBufRef.sampleAt(clientBufHead);
		unsigned danteBufferHead = mClientRxHead;
		for (unsigned sample = 0; sample < framesToTransfer; sample++)
		{
			// Copy the sample
			int32_t danteSample = mBufferView.getRxSample(mRxChannels.mFirstChannel + channel, danteBufferHead);
			convertFn(clientBufferHeadPtr, danteSample);

			// Advance temporary heads
			if (clientBufferHeadPtr == clientBufferLastPtr)
			{
				clientBufferHeadPtr = clientBufRef.sampleAt(0);
			}
			else
			{
				clientBufferHeadPtr += clientBufRef.mStrideBytes;
			}
			danteBufferHead = mBufferView.progressHead(danteBufferHead, 1);
		}
	}

	// Finally advance the shared head and the available count
	mClientRxHead = mBufferView.progressHead(mClientRxHead, framesToTransfer);
	mRxAvailable -= framesToTransfer;
	return framesToTransfer;
}

/// using BlockAccessFn = std::function<unsigned(unsigned numSamples, std::vector<int32_t *> channelPointers)>;
template <typename BlockAccessFn>
inline unsigned BufferBlockAccessor::accessTxBlock(const BlockAccessFn & blockAccessFn, unsigned framesToTransfer)
{
	if (mTxChannels.mNumChannels == 0)
	{
		throw std::invalid_argument("No TX channels configured");
	}

	std::vector<int32_t *> channelPointers(mTxChannels.mNumChannels, nullptr);

	framesToTransfer = clampTxFramesToTransfer(framesToTransfer);

	unsigned framesTransferred = 0;
	while (framesTransferred < framesToTransfer)
	{
		unsigned framesNow = framesToTransfer - framesTransferred;
		// Calculate how many frames we can transfer in this iteration
		if (mClientTxHead + framesNow > mBufferView.getBufferSizeFrames())
		{
			framesNow = mBufferView.getBufferSizeFrames() - mClientTxHead;
		}
		// Setup channel pointers
		for (unsigned channel = 0; channel < mTxChannels.mNumChannels; ++channel)
		{
			const BufferDescription & danteChannelBuf =
				mBufferView.getTxBufferDescription(mTxChannels.mFirstChannel + channel);
			channelPointers[channel] = reinterpret_cast<int32_t *>(danteChannelBuf.sampleAt(mClientTxHead));
		}
		unsigned actuallyTransferred = blockAccessFn(framesNow, channelPointers);
		mClientTxHead = mBufferView.progressHead(mClientTxHead, actuallyTransferred);
		mTxFramesToWrite -= static_cast<int>(actuallyTransferred);
		framesTransferred += actuallyTransferred;

		if (actuallyTransferred == 0)
		{
			break;
		}
	}
	return framesTransferred;
}

/// using BlockAccessFn = std::function<unsigned(unsigned numSamples, std::vector<int32_t *> channelPointers)>;
template <typename BlockAccessFn>
inline unsigned BufferBlockAccessor::accessRxBlock(const BlockAccessFn & blockAccessFn, unsigned framesToTransfer)
{
	if (mRxChannels.mNumChannels == 0)
	{
		throw std::invalid_argument("No RX channels configured");
	}

	std::vector<int32_t *> channelPointers(mRxChannels.mNumChannels, nullptr);

	if (framesToTransfer > mRxAvailable)
	{
		framesToTransfer = mRxAvailable;
	}

	unsigned framesTransferred = 0;
	while (framesTransferred < framesToTransfer && mRxAvailable > 0)
	{
		unsigned framesNow = framesToTransfer - framesTransferred;
		// Calculate how many frames we can transfer in this iteration
		if (mClientRxHead + framesNow > mBufferView.getBufferSizeFrames())
		{
			framesNow = mBufferView.getBufferSizeFrames() - mClientRxHead;
		}
		// Setup channel pointers
		for (unsigned channel = 0; channel < mRxChannels.mNumChannels; ++channel)
		{
			const BufferDescription & danteChannelBuf =
				mBufferView.getRxBufferDescription(mRxChannels.mFirstChannel + channel);
			channelPointers[channel] = reinterpret_cast<int32_t *>(danteChannelBuf.sampleAt(mClientRxHead));
		}
		unsigned actuallyTransferred = blockAccessFn(framesNow, channelPointers);
		mClientRxHead = mBufferView.progressHead(mClientRxHead, actuallyTransferred);
		mRxAvailable -= actuallyTransferred;
		framesTransferred += actuallyTransferred;

		if (actuallyTransferred == 0)
		{
			break;
		}
	}
	return framesTransferred;
}

} // namespace Dante
//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
