//
// Copyright © 2020-2024 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//

/// @file Buffers.hpp
/// Audio buffers header file
#pragma once

#include <cstdint>
#include <sys/types.h>
#ifdef WIN32
#include <Windows.h>
#include <inttypes.h>
#endif

#include <functional>
#include <string>
#include <vector>

#include <atomic>
#include <memory>

#include "DdhiClient.hpp"

#define DANTE_ENCODING__PCM32 32
#define DANTE_ENCODING__FLOAT32 65

/// If set, the meta-data header, TX and RX channel buffers are in seperate memory segments.
/// If not set, the meta-data header and channel buffers are in a single continuous memory segment.
#define DANTE_BUFFERS_FLAG__SEPARATE_CHANNEL_MEMORY 0x1

/// Set by DEP when updating multiple fields in the time struct that need to be read atomically
#define DANTE_BUFFERS_FLAG__TIMING_UPDATE_SYNC 0x10000

/// Special non-zero value used for header magic
#define DANTE_BUFFERS_HDR_MAGIC 0x50525354

namespace Dante
{

///
/// Overlay structure for the shared memory buffer header block
///
typedef struct buffer_header
{
	/// Describes the shared memory layout and state
	struct
	{
		/// Set to zero when the shared memory buffer is not yet configured or becomes invalid.
		/// Set to DANTE_BUFFERS_HDR_MAGIC when the shared memory buffer has been fully set
		/// up and is valid for use.
		uint32_t magic_marker;

		/// Total length in bytes of the shared memory. Includes headers and audio channel buffers.
		uint32_t buffer_length;

		/// Total length in bytes of the metadata header
		uint32_t metadata_header_length;

		/// Flags used for various buffer operations. See DANTE_BUFFERS_FLAG defines.
		uint32_t flags;

		/// Offset in bytes to the firxt TX channel buffer from the start of this header
		uint32_t first_tx_channel_offset_bytes;

		/// Offset in bytes to the firxt RX channel buffer from the start of this header
		uint32_t first_rx_channel_offset_bytes;

		/// Offset in bytes to the timing object subheader from the start of this header
		uint32_t timing_object_subheader_offset_bytes;

		/// Incremented at the start and end of a buffer reset operation
		uint32_t reset_count;
	} metadata;

	/// Describes the audio data stored in the channel buffers
	struct
	{
		/// When non-zero, this value is the currently configured device sample rate.
		/// When zero, it means the sample rate is in the process of being changed.
		uint32_t sample_rate;

		/// Encoding of the audio data in the channel buffers. Currently always DANTE_ENCODING__PCM32.
		uint32_t encoding;

		/// The total number of samples that can be stored in the buffers for each channel
		uint32_t samples_per_channel;

		/// Total size in bytes for each channel buffer
		uint32_t bytes_per_channel;

		/// Total number of available TX channels (minimum of configured and activated number of channels)
		uint32_t num_tx_channels;

		/// Total number of available RX channels (minimum of configured and activated number of channels) 
		uint32_t num_rx_channels;
		uint32_t pad7;
		uint32_t pad8;
	} audio;

	/// time fields
	struct
	{
		/// The epoch represents the PTP time at which the device last achieved PTP synchronisation.
		/// To get the complete epoch time, convert @ref epoch_seconds and @ref epoch_samples into the same units
		/// and add them together. For example, to get epoch time in samples:
		/// (epoch_seconds * sample_rate) + epoch_samples
		/// @note The epoch is initially zero when the device first starts up before it has achieved
		/// PTP sync for the first time. Subsequently the epoch values are only updated upon each sync
		/// event but not on sync loss. That is, this value cannot be used to determine the
		/// device's current PTP sync state apart from the initial state (yet to sync for the first time).
		uint32_t epoch_seconds;

		/// The sub-second portion of the epoch in unit of samples. See @ref epoch_seconds for more details.
		uint32_t epoch_samples;

		/// This value gives the number of samples that will elapse before DEP signals to the application
		/// that there is audio data available. A lower value can allow the application to wake up
		/// more often to process audio data but with the tradeoff that CPU load will increase.
		uint32_t samples_per_period;

		/// This value is incremented every time a period has elapsed.
		/// Applications can use this value to determine how many periods of audio data can be read/written
		/// since the last time it woke up.
		uint64_t period_count;

		/// Currently unused
		uint32_t clock_drift_ppb;

		/// The local monotonic time at the current period_count value.
		/// The montonic clock source is CLOCK_MONOTONIC_RAW.
		/// (monotonic, period_count) timing pair values can be used to track the rate change
		/// of the local time domain against the PTP time domain.
		/// @note The (monotonic, period_count) values are not updated atomically. But such updates are
		/// bracketed by setting DANTE_BUFFERS_FLAG__TIMING_UPDATE_SYNC prior to starting an update and cleared
		/// when both fields have been updated. See the DanteTiming example code for a guide to how
		/// these two timing fields can be read to ensure correctness and consistency.
		uint64_t monotonic;
	} time;

} buffer_header_t;

//----------------------------------------------------------
// Timing object subheader
//----------------------------------------------------------

#define TIMING_OBJECT_NAME_LENGTH 256

enum
{
	/// No timing synchronisation
	TIMING_OBJECT_TYPE__NONE = 0,

	/// Posix semaphore or Windows Event.
	/// DEP signals the semaphore/event after each period. See buffer_header_t.time.samples_per_period for more details.
	TIMING_OBJECT_TYPE__SIGNAL_EVENT = 1
};

/// Timing object subheader
///
/// Used to describe the timing synchronisation mechanism used between DEP and the application
typedef struct timing_object_subheader
{
	/// Length in bytes of this subheader
	uint32_t subheader_length_bytes;

	/// The timing object type. Currently only TIMING_OBJECT_TYPE__SIGNAL_EVENT is used.
	uint32_t object_type;

	/// Name of the timing object. The meaning of this name is dependent on the object type.
	/// If TIMING_OBJECT_TYPE__SIGNAL_EVENT is in use, this gives the name of the Posix semaphore
	/// or Windows signal event.
	char object_name[TIMING_OBJECT_NAME_LENGTH];
} timing_object_subheader_t;

using DisconnectionCallback = std::function<void(const std::string &)>;

//----------------------------------------------------------
// Platform-specific shared-memory implementation
//----------------------------------------------------------

class SharedMemory
{
public:
	SharedMemory();
	~SharedMemory();

	int connect(const std::string & name, bool globalNamespace, DisconnectionCallback requestDisconnectionCallback = nullptr);
	void disconnect();

	void * get() const;

	static std::string getErrorMessage(int err);

private:
	class Impl;
	Impl * mImpl;
};

///
// The main buffer handler class
///
class Buffers
{
public:
	Buffers();
	~Buffers();

	/// Attempt to connect to the underlying shared memory buffer(s)
	///
	/// @param name Name of the shared memory buffer to connect to
	/// @param globalNamespace true if the name is in a global namespace and false otherwise.
	/// Only relevant for Windows platforms.
	/// @param requestDisconnectionCallback callback for events that require the consumer of the memory to disconnect in a synchronous way.
	/// @return 0 on success, otherwise a platform-specific error code
	int connect(const std::string & name, bool globalNamespace, DisconnectionCallback requestDisconnectionCallback = nullptr);

	/// Attempt to connect to the underlying mapped file buffers
	///
	/// @param device Path to device/file where memory is mapped
	/// @param offset Offset at which memory is mapped
	/// @param requestDisconnectionCallback callback for events that require the consumer of the memory to disconnect in a synchronous way.
	/// @return 0 on success, otherwise a platform-specific error code
	int connect(const std::string & device, uintmax_t offset, DisconnectionCallback requestDisconnectionCallback = nullptr);

	/// Disconnect from the underlying shared memory buffer(s)
	void disconnect();

	/// Check whether currently connected to underlying shared memory buffer(s)
	/// @return true if connected and false otherwise
	bool isConnected() const { return mIsConnected; }

	/// Check whether shared memory is within a global name space.
	///
	/// @note Only relevant for Windows platforms.
	/// @return true if a global name space is in use and false otherwise.
	bool isGlobalNamespace() const;

	/// Get a pointer to the shared memory metadata block
	/// @return pointer to the start of the metadata block
	const volatile buffer_header_t * getHeader() const;

	/// Get a pointer to the shared memory timing object subheader
	/// @return pointer to the start of the timing object subheader
	const timing_object_subheader_t * getTimingObjectSubheader() const;

	/// Get audio buffer for the given Dante TX channel
	///
	/// Non-interleaved samples for the given TX channel can be written into the audio buffer
	/// @param index Zero based index of given Dante TX channel
	/// @return pointer to start of audio buffer for given index
	void * getDanteTxChannel(unsigned int index) const;

	/// Get audio buffer for the given Dante RX channel
	///
	/// Non-interleaved samples for the given RX channel can be read from the audio buffer
	/// @param index Zero based index of given Dante RX channel
	/// @return pointer to start of audio buffer for given index
	void * getDanteRxChannel(unsigned int index) const;

private:
	bool mGlobalNamespace;
	SharedMemory mSharedMemory;
	SharedMemory mDanteTxSharedMemory;
	SharedMemory mDanteRxSharedMemory;

	// cached data
	const volatile buffer_header_t * mHeader;
	const timing_object_subheader_t * mTimingObjectSubheader;
	std::vector<void *> mDanteTxChannels;
	std::vector<void *> mDanteRxChannels;

	bool mIsConnected;

	struct MappedFileBuffer
	{
		void * memory;
		size_t size;
	} mMappedFileBuffers;
};


//----------------------------------------------------------
// Platform-specific helper class that encapsulates run loop functionality 
//----------------------------------------------------------

class Timing
{
public:
	Timing();
	~Timing();

	int open(const timing_object_subheader_t * subheader, bool globalNamespace);
	void close();

	int wait();

	static std::string getErrorMessage(int err);

private:
	class Impl;
	Impl * mImpl;
};

class TelemetryConfig
{
public:
	TelemetryConfig() : mDdhi(true), mDdhiPath() {}

	TelemetryConfig(bool ddhi, const std::string & ddhiPath) : mDdhi(ddhi), mDdhiPath(ddhiPath) {}

	bool mDdhi;
	std::string mDdhiPath; // empty string means "use default"
};

class Telemetry
{
public:

	// Connect / disconnect triggers
	void start();
	void stop();

	// Telemetry triggers
	void sleep();
	void wake();
	Telemetry(const TelemetryConfig & config);
	~Telemetry() = default;
	
private:
	TelemetryConfig mConfig;
	uint64_t mLastWakeTime;
	uint64_t mCurrentWakeTime;

	uint64_t mMinInterval, mMaxInterval, mMinDuration, mMaxDuration;

	uint64_t mLastSendTimeSecs;

	std::shared_ptr<Ddhi::Client> mDdhiClient;

	void send();
};

typedef std::function<void (bool)> RunnerActiveChangedFn;

//----------------------------------------------------------
// Helper class that encapsulates run loop functionality 
//----------------------------------------------------------

class Runner
{
public:
	Runner(Buffers & buffers, bool ddhiTelemetry = true);
	~Runner();

	// run the main processing loop.
	// buffers must be connected. 
	// Runs until 'running' is set to false or the buffer magic marker is cleared,
	// indicating that a disconnection is required.
	int run(bool & running, std::function<void(unsigned int n)> transferFn, std::function<void()> epochResetFn);

	bool isActive() const;
	void setActiveChangedFn(RunnerActiveChangedFn fn) { mActiveChangedFn = fn; }

private:
	void setActive(bool active);
	int runInner(bool & running, std::function<void(unsigned int n)> transferFn, std::function<void()> epochResetFn);

	Buffers & mBuffers;
	const volatile buffer_header_t * mHeader;
	const timing_object_subheader_t * mTimingObjectSubheader;
	uint32_t mResetCount;
	uint64_t mPeriodCount;
	uint64_t mLastActiveMonotonicValue;
	bool mIsActive;
	RunnerActiveChangedFn mActiveChangedFn;

	Telemetry mTelemetry;
};

//----------------------------------------------------------
// Memory Barrier helper function
//----------------------------------------------------------

/*
 * The cpu and the compiler can reorder memory operations for the sake of optimisation.
 * However, this can break the synchronisation between DEP and the external application,
 * where we expect reads and writes to the shared memory to happen in a certain order.
 * 
 * An acquire barrier ensures that any reads or writes sequenced after the barrier
 * are ordered after any reads before the barrier. For example, DEP writes to the RX
 * buffers and then updates the header.audio.period_count. Consider this pseudocode for
 * reading from the buffer:
 * ```
 * while(period_count == previous_period_count);
 * memory_barrier_acquire();
 * read_audio_data();
 * ```
 * The memory barrier here guarantees that the data read in read_audio_data() will be
 * at least as recent as the write to the period_count.
 * 
 * This method is one way to implement an acquire memory barrier in a compiler and
 * architecture agnostic way. 
 */
#ifdef _WIN32
#pragma warning(push)
#pragma warning(disable: 4834) // ignore NODISCARD on dummyvar.load
#endif
static inline void memory_barrier_acquire() {
	volatile std::atomic<int> dummy_var;
	dummy_var.store(1);
	dummy_var.load(std::memory_order_relaxed);
	std::atomic_thread_fence(std::memory_order_acquire);
}
#ifdef _WIN32
#pragma warning(pop)
#endif

//----------------------------------------------------------
// Platform-specific helper functions
//----------------------------------------------------------

uint64_t getMonotonicRate();

uint64_t getMonotonicValue();

void sleepMs(unsigned int ms);

} // namespace Dante
//
// Copyright © 2020-2024 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
