//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//
// BufferView.hpp
// Interface for accessing Dante buffers
//

#pragma once

#include "dante/IDanteBuffers.hpp"
#include "dante/IDanteTiming.hpp"
#include "dante/Log.hpp"

#include <thread>

namespace Dante {

// Description of a channel within a buffer area (only supports sample formats that are a multiple of 8 bits)
// Allows for interleaved or non-interleaved buffers
struct BufferDescription
{
	uint8_t * const mBufAddr;
	const unsigned mFirstByte;
	const unsigned mStrideBytes;
	const unsigned mBufferSizeFrames;
	inline uint8_t * sampleAt(const unsigned offset) const { return mBufAddr + mFirstByte + mStrideBytes * offset; }
};

class BufferView
{
public:
	enum class State
	{
		// Dante::Buffers are not connected, or DEP is not running. Only `getState` and `poll` may be
		// called. Once Dante::Buffers are connected, polling may recover to CONNECTED or READY states.
		UNAVAILABLE,
		// Connected but audio and parameters not currently available. Only `getState` and `poll` may be called. May be
		// ready after waiting and polling again.
		CONNECTED,
		// Audio parameters are available and audio buffers can be read/written. May transition on `poll` to UNAVAILABLE
		// or CONNECTED if Dante disconnects or resets.
		READY
	};

	struct PeriodTimestamp
	{
		uint64_t mMonotonicNs; // The native monotonic time in nanoseconds when current period started
		uint64_t mPeriodCount; // The number of periods since this Dante epoch started

		bool operator==(const PeriodTimestamp & other) const
		{
			return mMonotonicNs == other.mMonotonicNs && mPeriodCount == other.mPeriodCount;
		}

		bool operator!=(const PeriodTimestamp & other) const { return !(*this == other); }
	};

	struct SampleTimestamp
	{
		uint64_t mMonotonicNs; // The native monotonic time in nanoseconds when current period started
		uint64_t mSampleCount; // The number of samples since this Dante epoch started

		bool operator==(const SampleTimestamp & other) const
		{
			return mMonotonicNs == other.mMonotonicNs && mSampleCount == other.mSampleCount;
		}

		bool operator!=(const SampleTimestamp & other) const { return !(*this == other); }
	};

	struct PollInfo
	{
		State mState;
		// Whether there has been a reset
		bool mReset;
		unsigned mSamplerate;
		unsigned mPeriodsSinceLastUpdate;
		unsigned mSamplesSinceLastUpdate;
		// These two values in the PeriodTimestamp are guaranteed to be collected atomically with respect to each other
		PeriodTimestamp mPeriodTimestamp;
		// At current the values in SampleTimestamp are just derived from the period timestamp, but this may change in the future
		SampleTimestamp mSampleTimestamp;
	};

	// Dante Buffers must be created and connected before creating BufferView
	BufferView(IDanteLogger & log, IDanteBuffers & buffers);

	~BufferView() = default;

	BufferView(const BufferView &) = delete;
	BufferView & operator=(const BufferView &) = delete;

	/// @brief Poll the Dante buffers for updates (may block briefly in rare situations). Typically called immediately
	///        after waiting on the timing object. Updates the view to the current buffer state.
	/// @note  The state can only change as a result of a poll, and if the state changes, the PollInfo will indicate a
	/// reset.
	/// @param info Output parameter with volatile elements of Dante buffer state
	void poll(PollInfo & info);

	/// @return The current state of this Dante buffer connector
	State getState() const { return mState; }

	/// @return The Dante period size in frames
	unsigned getPeriodSizeFrames() const { return mPeriodSizeFrames; }

	/// @return The Dante buffer size in frames
	unsigned getBufferSizeFrames() const { return mBufferSizeFrames; }

	/// @return The number of TX channels in the Dante buffers
	unsigned getTxChannelCount() const { return mNumTxChannels; }
	/// @return The number of RX channels in the Dante buffers
	unsigned getRxChannelCount() const { return mNumRxChannels; }

	/// @param channelIndex The channel index to get description for
	/// @return A BufferDescription for the given TX channel
	const BufferDescription & getTxBufferDescription(unsigned channelIndex) const
	{
		return mTxChannels.at(channelIndex);
	}

	/// @param channelIndex The channel index to get description for
	/// @return A BufferDescription for the given RX channel
	const BufferDescription & getRxBufferDescription(unsigned channelIndex) const
	{
		return mRxChannels.at(channelIndex);
	}

	/// @return The current Dante sample rate in Hz.
	unsigned getCurrentSamplerate() const { return mSamplerate; }

	/// @return Get the latest period count and associated monotonic count from the Dante buffers. Updated on poll()
	PeriodTimestamp getLatestPeriodTimeStamp() const { return mLastPeriodTimestamp; }

	/// @return Get the latest sample count and associated monotonic count from the Dante buffers. Updated on poll()
	SampleTimestamp getLatestSampleTimestamp() const { return mLastSampleTimestamp; }

	void setTxSample(unsigned channelIndex, unsigned sampleIndex, int32_t sample)
	{
		*reinterpret_cast<int32_t *>(mTxChannels[channelIndex].sampleAt(sampleIndex)) = sample;
	}

	int32_t getRxSample(unsigned channelIndex, unsigned sampleIndex) const
	{
		return *reinterpret_cast<const int32_t *>(mRxChannels[channelIndex].sampleAt(sampleIndex));
	}

	/// @brief Calculate new head position after progressing framesProcessed frames
	/// @param currentHead Current head position
	/// @param framesProcessed Number of frames to progress
	/// @return New head position, wrapped to Dante buffer size
	unsigned progressHead(unsigned currentHead, unsigned framesProcessed) const;

	/// @brief Util for calculating a new head position for an arbitrary buffer size
	/// @warning Assumes framesProcessed <= bufferSizeFrames
	static unsigned progressHead(unsigned currentHead, unsigned framesProcessed, unsigned bufferSizeFrames);

	/// @brief Calculate the Dante head position for the given period count and offset
	/// @param periodCount The current period timestamp from the Dante buffers
	/// @param offset Offset to add to the calculated head position measured in frames
	/// @return The calculated head position (in the range [0, buffer size in frames) )
	unsigned calcHeadPosition(PeriodTimestamp periodStamp, unsigned offset);

	/// @brief Calculate the Dante head position for the given sample count and offset
	/// @param sampleStamp The current sample timestamp from the Dante buffers
	/// @param offset Offset to add to the calculated head position measured in frames
	/// @return The calculated head position (in the range [0, buffer size in frames) )
	unsigned calcHeadPosition(SampleTimestamp sampleStamp, unsigned offset);

	/// @brief Get a consistent snapshot of the Dante timestamp. May block
	/// @note It's recommended to use the timestamp provided by poll().
	PeriodTimestamp getTimestampAtomicSafe();

private:
	PeriodTimestamp getCurrentTimestamp();

	void changeState(State newState);
	bool isDanteConnected() const;
	/// @brief Handle Dante buffer reset. Also called on initialisation.
	void reset();
	/// @brief Clear the view's cached state
	void clear();

	void createChannelDescriptions();

	IDanteLogger & mLog;
	State mState = State::UNAVAILABLE;

	IDanteBuffers & mBuffers;
	// Convenience pointer to the Dante buffer header
	const volatile Dante::buffer_header_t * mHeaderPtr;

	// Buffer geometry
	unsigned mPeriodSizeFrames = 0;
	unsigned mBufferSizeFrames = 0;
	unsigned mNumTxChannels = 0;
	unsigned mNumRxChannels = 0;

	std::vector<BufferDescription> mTxChannels;
	std::vector<BufferDescription> mRxChannels;

	// Volatile header values cached after poll()
	unsigned mResetCount = 0;
	unsigned mSamplerate = 0;
	PeriodTimestamp mLastPeriodTimestamp = {0, 0};
	SampleTimestamp mLastSampleTimestamp = {0, 0};
};

// ======================================================
// BufferView implementation
// ======================================================

inline BufferView::BufferView(IDanteLogger & log, IDanteBuffers & buffers)
	: mLog(log),
	  mBuffers(buffers)
{
	if (!isDanteConnected())
	{
		return;
	}

	// Set the state to connected. The first poll may transition to READY.
	mHeaderPtr = mBuffers.getBufferHeader();
	changeState(State::CONNECTED);
}

inline BufferView::PeriodTimestamp BufferView::getCurrentTimestamp()
{
	PeriodTimestamp timestamp;
	timestamp.mPeriodCount = mHeaderPtr->time.period_count;
	timestamp.mMonotonicNs = mHeaderPtr->time.monotonic;
	return timestamp;
}

/// @brief Locklessly get a consistent snapshot of the Dante timestamp
/// @warning In the specific case where the APE process is on the same core as this, and this process has a higher RT
/// 	priority, and we pre-empted the APE while it was updating the timestamp, it is possible this will be forced to
/// 	sleep to allow the APE process to run.
/// @return A consistent timestamp snapshot
inline BufferView::PeriodTimestamp BufferView::getTimestampAtomicSafe()
{
	PeriodTimestamp timestamp;
	PeriodTimestamp backupTimestamp;
	uint32_t retries = 0;
	timestamp = getCurrentTimestamp();
	Dante::memory_barrier_acquire();
	bool currentlyUpdating = (mHeaderPtr->metadata.flags & DANTE_BUFFERS_FLAG__TIMING_UPDATE_SYNC) != 0;
	Dante::memory_barrier_acquire();
	backupTimestamp = getCurrentTimestamp();

	// If both reads are the same, then either no update was in progress or we pre-empted an update
	// In the latter case, the TIMING_UPDATE_SYNC flag would have been set.
	// In practice, this has incredibly low rate of occurrence.
	while (currentlyUpdating || timestamp != backupTimestamp)
	{
		retries++;
		// Try again
		timestamp = backupTimestamp;
		Dante::memory_barrier_acquire();
		currentlyUpdating = (mHeaderPtr->metadata.flags & DANTE_BUFFERS_FLAG__TIMING_UPDATE_SYNC) != 0;
		Dante::memory_barrier_acquire();
		backupTimestamp = getCurrentTimestamp();
		if (retries % 100 == 0)
		{
			// If we have a high RT priority, std::this_thread::yield() may not be sufficient to allow the APE process
			// to run
			std::this_thread::sleep_for(std::chrono::microseconds(1));
		}
	}
	return timestamp;
}

/// @brief We want mState == UNAVAILABLE if and only if !isDanteConnected()
inline bool BufferView::isDanteConnected() const
{
	if (!mBuffers.isConnected())
	{
		return false;
	}
	if (mBuffers.getBufferHeader()->metadata.magic_marker != DANTE_BUFFERS_HDR_MAGIC)
	{
		return false;
	}
	return true;
}

inline void BufferView::changeState(State newState)
{
	if (newState == State::UNAVAILABLE)
	{
		clear();
		return;
	}
	if (newState != State::READY)
	{
		mSamplerate = 0;
	}
	mState = newState;
}

inline void BufferView::clear()
{
	mHeaderPtr = nullptr;
	mPeriodSizeFrames = 0;
	mBufferSizeFrames = 0;
	mNumTxChannels = 0;
	mNumRxChannels = 0;
	mTxChannels.clear();
	mRxChannels.clear();
	mSamplerate = 0;
	mLastPeriodTimestamp = {0, 0};
	mLastSampleTimestamp = {0, 0};
	mState = State::UNAVAILABLE;
}

/// @precondition: Dante buffers are connected and mHeaderPtr is valid. This function is to determine whether we are in
/// CONNECTED or READY
inline void BufferView::reset()
{
	mResetCount = mHeaderPtr->metadata.reset_count;

	// If mHeaderPtr->metadata.reset_count is odd, a reset is in progress
	// Set state to CONNECTED to indicate that audio is not flowing,
	// but the client application can wait() for it to become READY
	if (mResetCount & 0x1)
	{
		changeState(State::CONNECTED);
		return;
	}

	// Ensure the read of metadata is after the read from reset_count
	Dante::memory_barrier_acquire();

	mSamplerate = mHeaderPtr->audio.sample_rate;
	if (mSamplerate != 0)
	{
		changeState(State::READY);
	}
	else
	{
		// Network time is not available or sample rate is in the process of changing
		changeState(State::CONNECTED);
		return;
	}

	// We only support PCM32
	if (mHeaderPtr->audio.encoding != DANTE_ENCODING__PCM32)
	{
		mLog.log(LogLevel::ERROR, "%s: Unsupported Dante encoding: %u", __func__, mHeaderPtr->audio.encoding);
		changeState(State::UNAVAILABLE);
		return;
	}

	// Cache buffer geometry and descriptions
	mPeriodSizeFrames = mHeaderPtr->time.samples_per_period;
	mBufferSizeFrames = mHeaderPtr->audio.samples_per_channel;
	mNumTxChannels = mHeaderPtr->audio.num_tx_channels;
	mNumRxChannels = mHeaderPtr->audio.num_rx_channels;
	createChannelDescriptions();

	mLastPeriodTimestamp = getTimestampAtomicSafe();
	mLastSampleTimestamp = {mLastPeriodTimestamp.mMonotonicNs, mLastPeriodTimestamp.mPeriodCount * mPeriodSizeFrames};

	// Ensure that the timestamp read is before any reads from the audio buffers
	Dante::memory_barrier_acquire();
}

inline void BufferView::poll(PollInfo & info)
{
	info.mPeriodTimestamp = {0, 0};
	info.mSampleTimestamp = {0, 0};
	info.mSamplesSinceLastUpdate = 0;
	info.mSamplerate = 0;

	if (!isDanteConnected())
	{
		changeState(State::UNAVAILABLE);
		info.mState = mState;
		info.mReset = true;
		return;
	}
	else if (mState == State::UNAVAILABLE)
	{
		// If the buffers were previously unavailable, but Dante is now connected, make sure mHeaderPtr is valid
		// and reset below to get the correct state
		mHeaderPtr = mBuffers.getBufferHeader();
	}

	// Check for reset
	if (mHeaderPtr->metadata.reset_count != mResetCount || mState != State::READY)
	{
		info.mReset = true;
		reset();
		info.mPeriodTimestamp = mLastPeriodTimestamp;
		info.mSampleTimestamp = mLastSampleTimestamp;
		info.mState = mState;
		info.mSamplerate = mSamplerate;
		// On reset, periodsSinceLastUpdate is zero
		return;
	}
	info.mReset = false;
	info.mState = mState;
	info.mSamplerate = mSamplerate;

	// Update the timestamp and calculate samples since last update
	PeriodTimestamp newTimestamp;
	newTimestamp = getTimestampAtomicSafe();
	info.mPeriodTimestamp = newTimestamp;
	uint64_t currentPeriodCount = newTimestamp.mPeriodCount;
	info.mPeriodsSinceLastUpdate = static_cast<unsigned>(currentPeriodCount - mLastPeriodTimestamp.mPeriodCount);

	// For now, sample counts are just based on period counts. This may change in the future
	uint64_t currentSampleCount = currentPeriodCount * mPeriodSizeFrames;
	info.mSamplesSinceLastUpdate = static_cast<unsigned>(currentSampleCount - mLastSampleTimestamp.mSampleCount);

	mLastPeriodTimestamp = newTimestamp;
	mLastSampleTimestamp = {mLastPeriodTimestamp.mMonotonicNs, currentSampleCount};
	info.mSampleTimestamp = mLastSampleTimestamp;

	// Ensure reads from the header are before reading audio data
	Dante::memory_barrier_acquire();
}

inline unsigned BufferView::calcHeadPosition(PeriodTimestamp periodStamp, unsigned offset)
{
	return static_cast<unsigned>((periodStamp.mPeriodCount * mPeriodSizeFrames + offset) % mBufferSizeFrames);
}

inline unsigned BufferView::calcHeadPosition(SampleTimestamp sampleStamp, unsigned offset)
{
	return static_cast<unsigned>((sampleStamp.mSampleCount + offset) % mBufferSizeFrames);
}

inline unsigned BufferView::progressHead(unsigned currentHead, unsigned framesProcessed, unsigned bufferSizeFrames)
{
	unsigned newHead = currentHead + framesProcessed;
	if (newHead >= bufferSizeFrames)
	{
		newHead -= bufferSizeFrames;
	}
	return newHead;
}

inline unsigned BufferView::progressHead(unsigned currentHead, unsigned framesProcessed) const
{
	return progressHead(currentHead, framesProcessed, mBufferSizeFrames);
}

inline void BufferView::createChannelDescriptions()
{
	mTxChannels.clear();
	mRxChannels.clear();
	for (unsigned i = 0; i < mNumTxChannels; ++i)
	{
		mTxChannels.push_back(

			BufferDescription{
				reinterpret_cast<uint8_t *>(mBuffers.getDanteTxChannel(i)),
				0,
				sizeof(int32_t),
				mBufferSizeFrames});
	}
	
	for (unsigned i = 0; i < mNumRxChannels; ++i)
	{
		mRxChannels.push_back(
			BufferDescription{
				reinterpret_cast<uint8_t *>(mBuffers.getDanteRxChannel(i)),
				0,
				sizeof(int32_t),
				mBufferSizeFrames});
	}
}

} // namespace Dante
//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
