//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//
// BufferContext.hpp
// Default context for Dante buffer access
//

#pragma once

#include "dante/BufferBlockAccessor.hpp"
#include "dante/BufferView.hpp"
#include "dante/Buffers.hpp"

#include <memory>

namespace Dante {

/// @brief Basic context which connects to the Dante buffers and timing object, and provides a view into the buffers.
/// Provides helper functions for connecting and polling the buffers.
class DefaultBufferContext
{
public:
	struct WaitResult
	{
		BufferView::PollInfo pollInfo;
		// Zero returns (meaning no error) are omitted
		std::vector<std::pair<BufferBlockAccessor*, int>> accessorLateValues;

		bool hasErrors() const
		{
			return !accessorLateValues.empty();
		}
	};


	/// @param inactiveTimeoutMs Number of milliseconds of inactivity (no new audio data) before automatically disconnecting. If negative, wait indefinitely.
	/// @param ddhiTelemetry Whether to enable telemetry for DDHI.
	/// Logs to stdout with timestamps by default
	DefaultBufferContext(int inactiveTimeoutMs = -1, bool ddhiTelemetry = true)
		: mLog(std::make_shared<PrintfLogger>(LogLevel::WARNING)),
		  mBufferAdapter(mBuffers),
		  mBufferView(*mLog, mBufferAdapter),
		  mInactiveTimeoutMs(inactiveTimeoutMs),
		  mTelemetry(TelemetryConfig(ddhiTelemetry, ""))
	{}

	/// @param inactiveTimeoutMs Number of milliseconds of inactivity (no new audio data) before automatically disconnecting. If negative, wait indefinitely.
	/// @param ddhiTelemetry Whether to enable telemetry for DDHI.
	/// @param log Logs go to the provided logger
	DefaultBufferContext(std::shared_ptr<IDanteLogger> log, int inactiveTimeoutMs = -1, bool ddhiTelemetry = true)
		: mLog(log ? log : std::make_shared<PrintfLogger>(LogLevel::WARNING)),
		  mBufferAdapter(mBuffers),
		  mBufferView(*mLog, mBufferAdapter),
		  mInactiveTimeoutMs(inactiveTimeoutMs),
		  mTelemetry(TelemetryConfig(ddhiTelemetry, ""))
	{}

	~DefaultBufferContext() = default;

	/// @brief Connect to the mapped file buffers. Blocks until successful or timeout.
	/// @param device Path to device/file where memory is mapped
	/// @param offset Offset at which memory is mapped
	/// @param timeoutSecs Number of seconds to wait before giving up. If negative, wait indefinitely.
	/// @return 0 on success, 1 on failure
	int connect(const std::string & device, uintmax_t offset, int timeoutSecs)
	{
		return connect([this, device, offset]() { return mBuffers.connect(device, offset); }, timeoutSecs);
	}

	/// @brief Tries to connect to the Dante buffers. Blocks until successful or timeout.
	/// @param shmName Name of the Dante shared memory buffer
	/// @param globalNamespace Whether the Dante buffer is in the global namespace
	/// @param timeoutSecs Number of seconds to wait before giving up. If negative, wait indefinitely.
	/// @return 0 on success, 1 on failure
	int connect(const std::string & shmName, bool globalNamespace, int timeoutSecs)
	{
		return connect(
			[this, shmName, globalNamespace]() { return mBuffers.connect(shmName, globalNamespace); },
			timeoutSecs);
	}

	bool isConnected() const { return mBuffers.isConnected(); }

	BufferView::PollInfo disconnect()
	{
		mTelemetry.stop();
		mTiming.close();
		mBuffers.disconnect();
		// Polling the BufferView will now show UNAVAILABLE.
		// Propagate this to block accessors to clear available.
		BufferView::PollInfo info;
		mBufferView.poll(info);
		for (auto & accessor : mBlockAccessors)
		{
			accessor->updateAvailable(info);
		}
		return info;
	}

	/// @brief Wait for Dante audio to be available and update the BufferView and registered BlockAccessors. Must be connected before waiting
	/// @postcondition: The BufferView is either READY or UNAVAILABLE. If UNAVAILABLE, the context is disconnected.
	/// @return PollInfo structure containing the current state of the buffer view and any late warnings from the block accessors.
	WaitResult wait()
	{
		WaitResult result;
		if (!isConnected())
		{
			throw std::runtime_error("Dante buffers not connected");
		}
		std::chrono::steady_clock::time_point endTime = mLastActiveTime + std::chrono::milliseconds(mInactiveTimeoutMs);
		do
		{
			mTelemetry.sleep(); // Get duration since last wake. Will be very short if currently resetting.
			mTiming.wait();
			mTelemetry.wake(); // Get a timestamp when OEM starts processing
			mBufferView.poll(result.pollInfo);
		}
		while (result.pollInfo.mState == BufferView::State::CONNECTED && (mInactiveTimeoutMs < 0 || std::chrono::steady_clock::now() < endTime));
		// Note that the first poll after going to the READY state will always be a reset.

		if (result.pollInfo.mState == BufferView::State::UNAVAILABLE)
		{
			result.pollInfo = disconnect();
			return result;
		}

		if (result.pollInfo.mState == BufferView::State::CONNECTED)
		{
			// We timed out waiting for Dante to become ready. Disconnect and return.
			mLog->log(LogLevel::WARNING, "Dante buffers did not become ready within %d ms, disconnecting...", mInactiveTimeoutMs);
			result.pollInfo = disconnect();
			return result;
		}

		// We are in the READY state (otherwise we would have timed out/disconnected above).
		if (result.pollInfo.mSamplesSinceLastUpdate == 0)
		{
			// No new data, if we've been inactive for long enough, disconnect.
			if (mInactiveTimeoutMs >= 0 && std::chrono::steady_clock::now() >= endTime)
			{
				mLog->log(LogLevel::WARNING, "Dante buffers inactive for %d ms, disconnecting...", mInactiveTimeoutMs);
				result.pollInfo = disconnect();
				return result;
			}

			if (!result.pollInfo.mReset)
			{
				// No update, don't bother updating block accessors.
				return result;
			}
		}

		// Two cases here:
		// 1. We have audio data to read or write
		// 2. We had a reset but are now READY.
		mLastActiveTime = std::chrono::steady_clock::now();

		// Pass the pollInfo info to each block accessor
		for (auto & accessor : mBlockAccessors)
		{
			int late = accessor->updateAvailable(result.pollInfo);
			if (late != 0)
			{
				result.accessorLateValues.push_back({accessor, late});
			}
		}
		return result;
	}

	/// @note Lifetime of this reference is tied to the context. It is guaranteed to continue to exist
	/// 	 while the context is connected.
	BufferView & getBufferView()
	{
		return mBufferView;
	}

	/// @brief Register a block accessor to receive updates on buffer availability when polling.
	/// @param accessor Pointer to the block accessor to register.
	void registerBlockAccessor(BufferBlockAccessor * accessor)
	{
		mBlockAccessors.push_back(accessor);
	}

	/// @brief Deregister a block accessor to stop receiving updates on buffer availability.
	/// @param accessor Pointer to the block accessor to deregister.
	void deregisterBlockAccessor(BufferBlockAccessor * accessor)
	{
		mBlockAccessors.erase(std::remove(mBlockAccessors.begin(), mBlockAccessors.end(), accessor), mBlockAccessors.end());
	}

private:
	// Helper to connect to Dante buffers with a custom function. See connect() for details.
	int connect(std::function<int()> connectFn, int timeoutSecs)
	{
		int err = 0;
		const auto startTime = std::chrono::steady_clock::now();
		while (true)
		{
			err = connectFn();
			if (err == 0)
			{
				break;
			}
			mLog->log(
				LogLevel::WARNING,
				"Failed to connect to Dante buffers: %s. Retrying...",
				Dante::SharedMemory::getErrorMessage(err).c_str());

			const auto elapsed = std::chrono::steady_clock::now() - startTime;
			if (timeoutSecs >= 0 && std::chrono::duration_cast<std::chrono::seconds>(elapsed).count() >= timeoutSecs)
			{
				mLog->log(LogLevel::ERROR, "Timed out trying to connect to Dante buffers");
				return 1;
			}

			std::this_thread::sleep_for(std::chrono::seconds(1));
		}

		err = mTiming.open(mBuffers.getTimingObjectSubheader(), mBuffers.isGlobalNamespace());
		if (err != 0)
		{
			mBuffers.disconnect();
			mLog->log(LogLevel::ERROR, "Failed to open Dante timing object");
			return 1;
		}

		mTelemetry.start();
		// Get an initial timestamp for telemetry right away
		mTelemetry.wake();

		mLastActiveTime = std::chrono::steady_clock::now();

		return 0;
	}

	Dante::Buffers mBuffers;
	Dante::DanteBuffersAdapter mBufferAdapter;
	Dante::Timing mTiming;

	std::shared_ptr<IDanteLogger> mLog;
	BufferView mBufferView;
	std::vector<BufferBlockAccessor *> mBlockAccessors = {};

	int mInactiveTimeoutMs;
	std::chrono::steady_clock::time_point mLastActiveTime;

	Dante::Telemetry mTelemetry;
};

} // namespace Dante
//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
