//
// Copyright © 2020-2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//
// DanteAudio.hpp -- Consolidated Dante DEP SDK header, trimmed to the subset used by the JUCE loopback backend.
//

#pragma once

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <functional>
#include <memory>
#include <string>
#include <stdexcept>
#include <thread>
#include <vector>
#include <sys/types.h>

#ifdef WIN32
#include <Windows.h>
#include <inttypes.h>
#endif

// ==============================================================================
// Buffer types, shared memory, and timing
// ==============================================================================

#define DANTE_ENCODING__PCM32    32
#define DANTE_ENCODING__FLOAT32  65

#define DANTE_BUFFERS_FLAG__SEPARATE_CHANNEL_MEMORY  0x1
#define DANTE_BUFFERS_FLAG__TIMING_UPDATE_SYNC       0x10000
#define DANTE_BUFFERS_HDR_MAGIC                      0x50525354

#define TIMING_OBJECT_NAME_LENGTH 256

namespace Dante {

typedef struct buffer_header
{
    struct
    {
        uint32_t magic_marker;
        uint32_t buffer_length;
        uint32_t metadata_header_length;
        uint32_t flags;
        uint32_t first_tx_channel_offset_bytes;
        uint32_t first_rx_channel_offset_bytes;
        uint32_t timing_object_subheader_offset_bytes;
        uint32_t reset_count;
    } metadata;

    struct
    {
        uint32_t sample_rate;
        uint32_t encoding;
        uint32_t samples_per_channel;
        uint32_t bytes_per_channel;
        uint32_t num_tx_channels;
        uint32_t num_rx_channels;
        uint32_t pad7;
        uint32_t pad8;
    } audio;

    struct
    {
        uint32_t epoch_seconds;
        uint32_t epoch_samples;
        uint32_t samples_per_period;
        uint64_t period_count;
        uint32_t clock_drift_ppb;
        uint64_t monotonic;
    } time;

} buffer_header_t;

enum
{
    TIMING_OBJECT_TYPE__NONE         = 0,
    TIMING_OBJECT_TYPE__SIGNAL_EVENT = 1
};

typedef struct timing_object_subheader
{
    uint32_t subheader_length_bytes;
    uint32_t object_type;
    char     object_name[TIMING_OBJECT_NAME_LENGTH];
} timing_object_subheader_t;

using DisconnectionCallback = std::function<void(const std::string &)>;

class SharedMemory
{
public:
    SharedMemory();
    ~SharedMemory();

    int  connect(const std::string & name, bool globalNamespace,
                 DisconnectionCallback requestDisconnectionCallback = nullptr);
    void disconnect();
    void * get() const;

    static std::string getErrorMessage(int err);

private:
    class Impl;
    Impl * mImpl;
};

class Buffers
{
public:
    Buffers();
    ~Buffers();

    int  connect(const std::string & name, bool globalNamespace,
                 DisconnectionCallback requestDisconnectionCallback = nullptr);
    void disconnect();

    bool isConnected()       const { return mIsConnected; }
    bool isGlobalNamespace() const;

    const volatile buffer_header_t *  getHeader()                const;
    const timing_object_subheader_t * getTimingObjectSubheader() const;
    void * getDanteTxChannel(unsigned int index) const;
    void * getDanteRxChannel(unsigned int index) const;

private:
    bool         mGlobalNamespace;
    SharedMemory mSharedMemory;
    SharedMemory mDanteTxSharedMemory;
    SharedMemory mDanteRxSharedMemory;

    const volatile buffer_header_t *  mHeader;
    const timing_object_subheader_t * mTimingObjectSubheader;
    std::vector<void *>               mDanteTxChannels;
    std::vector<void *>               mDanteRxChannels;

    bool mIsConnected;

    struct MappedFileBuffer { void * memory; size_t size; } mMappedFileBuffers;
};

class Timing
{
public:
    Timing();
    ~Timing();

    int  open(const timing_object_subheader_t * subheader, bool globalNamespace);
    void close();
    int  wait();

    static std::string getErrorMessage(int err);

private:
    class Impl;
    Impl * mImpl;
};

// Must be inline: performance-critical barrier used in hot audio path
#ifdef _WIN32
#pragma warning(push)
#pragma warning(disable: 4834)
#endif
static inline void memory_barrier_acquire()
{
    volatile std::atomic<int> dummy_var;
    dummy_var.store(1);
    dummy_var.load(std::memory_order_relaxed);
    std::atomic_thread_fence(std::memory_order_acquire);
}
#ifdef _WIN32
#pragma warning(pop)
#endif

} // namespace Dante

// ==============================================================================
// Logging
// ==============================================================================

#if defined(__GNUC__) || defined(__clang__)
#define DANTE_PRINTF_LIKE(fmt_index, first_arg) __attribute__((format(printf, fmt_index, first_arg)))
#else
#define DANTE_PRINTF_LIKE(fmt_index, first_arg)
#endif

namespace Dante {

enum class LogLevel { NONE = 0, ERROR, WARNING, INFO, DEBUG };

std::string toString(LogLevel level);
LogLevel    fromString(const std::string & str);

class IDanteLogger
{
public:
    virtual ~IDanteLogger() = default;
    virtual void log(LogLevel level, const char * format, ...) DANTE_PRINTF_LIKE(3, 4) = 0;
};

class PrintfLogger : public IDanteLogger
{
public:
    PrintfLogger(LogLevel threshold) : mThreshold(threshold) {}
    virtual ~PrintfLogger() = default;

    void log(LogLevel level, const char * format, ...) override DANTE_PRINTF_LIKE(3, 4);

private:
    LogLevel mThreshold;
};

} // namespace Dante

// ==============================================================================
// IDanteBuffers
// ==============================================================================

namespace Dante {

class IDanteBuffers
{
public:
    virtual ~IDanteBuffers() = default;

    virtual bool isConnected() const = 0;
    virtual const volatile buffer_header_t *  getBufferHeader()          const = 0;
    virtual const timing_object_subheader_t * getTimingObjectSubheader() const = 0;
    virtual void * getDanteTxChannel(unsigned int index) const = 0;
    virtual void * getDanteRxChannel(unsigned int index) const = 0;
};

class DanteBuffersAdapter : public IDanteBuffers
{
public:
    DanteBuffersAdapter(Dante::Buffers & buffers) : mBuffers(buffers) {}

    bool isConnected() const override { return mBuffers.isConnected(); }

    const volatile buffer_header_t * getBufferHeader() const override
        { return mBuffers.getHeader(); }

    const timing_object_subheader_t * getTimingObjectSubheader() const override
        { return mBuffers.getTimingObjectSubheader(); }

    void * getDanteTxChannel(unsigned int index) const override
        { return mBuffers.getDanteTxChannel(index); }

    void * getDanteRxChannel(unsigned int index) const override
        { return mBuffers.getDanteRxChannel(index); }

private:
    Dante::Buffers & mBuffers;
};

} // namespace Dante

// ==============================================================================
// BufferView
// ==============================================================================

namespace Dante {

struct BufferDescription
{
    uint8_t * const mBufAddr;
    const unsigned  mFirstByte;
    const unsigned  mStrideBytes;
    const unsigned  mBufferSizeFrames;

    uint8_t * sampleAt(unsigned offset) const
        { return mBufAddr + mFirstByte + mStrideBytes * offset; }
};

class BufferView
{
public:
    enum class State { UNAVAILABLE, CONNECTED, READY };

    struct PeriodTimestamp
    {
        uint64_t mMonotonicNs;
        uint64_t mPeriodCount;
        bool operator==(const PeriodTimestamp & o) const
            { return mMonotonicNs == o.mMonotonicNs && mPeriodCount == o.mPeriodCount; }
        bool operator!=(const PeriodTimestamp & o) const { return !(*this == o); }
    };

    struct SampleTimestamp
    {
        uint64_t mMonotonicNs;
        uint64_t mSampleCount;
        bool operator==(const SampleTimestamp & o) const
            { return mMonotonicNs == o.mMonotonicNs && mSampleCount == o.mSampleCount; }
        bool operator!=(const SampleTimestamp & o) const { return !(*this == o); }
    };

    struct PollInfo
    {
        State    mState;
        bool     mReset;
        unsigned mSamplerate;
        unsigned mPeriodsSinceLastUpdate;
        unsigned mSamplesSinceLastUpdate;
        PeriodTimestamp mPeriodTimestamp;
        SampleTimestamp mSampleTimestamp;
    };

    BufferView(IDanteLogger & log, IDanteBuffers & buffers);
    ~BufferView() = default;
    BufferView(const BufferView &)             = delete;
    BufferView & operator=(const BufferView &) = delete;

    void  poll(PollInfo & info);
    State getState()               const { return mState; }
    unsigned getPeriodSizeFrames() const { return mPeriodSizeFrames; }
    unsigned getBufferSizeFrames() const { return mBufferSizeFrames; }
    unsigned getTxChannelCount()   const { return mNumTxChannels; }
    unsigned getRxChannelCount()   const { return mNumRxChannels; }
    unsigned getCurrentSamplerate() const { return mSamplerate; }

    const BufferDescription & getTxBufferDescription(unsigned channelIndex) const
        { return mTxChannels.at(channelIndex); }
    const BufferDescription & getRxBufferDescription(unsigned channelIndex) const
        { return mRxChannels.at(channelIndex); }

    PeriodTimestamp getLatestPeriodTimeStamp() const { return mLastPeriodTimestamp; }
    SampleTimestamp getLatestSampleTimestamp() const { return mLastSampleTimestamp; }

    void setTxSample(unsigned channelIndex, unsigned sampleIndex, int32_t sample)
        { *reinterpret_cast<int32_t *>(mTxChannels[channelIndex].sampleAt(sampleIndex)) = sample; }

    int32_t getRxSample(unsigned channelIndex, unsigned sampleIndex) const
        { return *reinterpret_cast<const int32_t *>(mRxChannels[channelIndex].sampleAt(sampleIndex)); }

    unsigned        progressHead(unsigned head, unsigned frames) const;
    static unsigned progressHead(unsigned head, unsigned frames, unsigned bufSize);
    unsigned        calcHeadPosition(PeriodTimestamp periodStamp, unsigned offset);
    unsigned        calcHeadPosition(SampleTimestamp sampleStamp, unsigned offset);
    PeriodTimestamp getTimestampAtomicSafe();

private:
    PeriodTimestamp getCurrentTimestamp();
    void changeState(State newState);
    bool isDanteConnected() const;
    void reset();
    void clear();
    void createChannelDescriptions();

    IDanteLogger &  mLog;
    State           mState   = State::UNAVAILABLE;
    IDanteBuffers & mBuffers;

    const volatile buffer_header_t * mHeaderPtr = nullptr;

    unsigned mPeriodSizeFrames = 0;
    unsigned mBufferSizeFrames = 0;
    unsigned mNumTxChannels    = 0;
    unsigned mNumRxChannels    = 0;

    std::vector<BufferDescription> mTxChannels;
    std::vector<BufferDescription> mRxChannels;

    unsigned        mResetCount          = 0;
    unsigned        mSamplerate          = 0;
    PeriodTimestamp mLastPeriodTimestamp = {0, 0};
    SampleTimestamp mLastSampleTimestamp = {0, 0};
};

} // namespace Dante

// ==============================================================================
// BufferBlockAccessor
// ==============================================================================

namespace Dante {

struct ChannelBlockDescription
{
    unsigned mFirstChannel;
    unsigned mNumChannels;
};

struct BlockAccessorConfig
{
    unsigned mTxLatencyUs      = 10000;
    unsigned mTxLatencySamples = 0;

    BlockAccessorConfig() = default;
    BlockAccessorConfig(unsigned txLatencyUs) : mTxLatencyUs(txLatencyUs) {}
};

class BufferBlockAccessor
{
public:
    BufferBlockAccessor(BufferView & bufferView, const BlockAccessorConfig & config);
    ~BufferBlockAccessor() = default;

    void setChannels(const ChannelBlockDescription & txChannels,
                     const ChannelBlockDescription & rxChannels);
    void setChannels(bool symmetric = false);

    int      getTxFramesToWrite() const { return mTxFramesToWrite; }
    unsigned getAvailRxFrames()   const { return mRxAvailable; }

    unsigned fastForwardTx(unsigned framesToDrop)
    {
        framesToDrop      = clampTxFramesToTransfer(framesToDrop);
        mClientTxHead     = mBufferView.progressHead(mClientTxHead, framesToDrop);
        mTxFramesToWrite -= framesToDrop;
        return framesToDrop;
    }

    unsigned fastForwardRx(unsigned framesToDrop)
    {
        if (framesToDrop > mRxAvailable) framesToDrop = mRxAvailable;
        mClientRxHead = mBufferView.progressHead(mClientRxHead, framesToDrop);
        mRxAvailable -= framesToDrop;
        return framesToDrop;
    }

    int updateAvailable(const BufferView::PollInfo & info);
    void resetClientHeads();

    // Templates must be defined in the header
    template <typename BlockAccessFn>
    unsigned accessTxBlock(const BlockAccessFn & fn, unsigned framesToTransfer);

    template <typename BlockAccessFn>
    unsigned accessRxBlock(const BlockAccessFn & fn, unsigned framesToTransfer);

private:
    void     reset(unsigned sampleRate);
    unsigned clampTxFramesToTransfer(unsigned n) const;
    void     resetTxClientHead();
    void     resetRxClientHead();

    BufferView & mBufferView;

    const unsigned mTxLatencyUs;
    const unsigned mConfiguredTxLatencySamples;

    ChannelBlockDescription mTxChannels      = {0, 0};
    ChannelBlockDescription mRxChannels      = {0, 0};

    unsigned mClientTxHead    = 0;
    unsigned mClientRxHead    = 0;
    int      mTxFramesToWrite = 0;
    unsigned mRxAvailable     = 0;
    unsigned mTxLatencyFrames = 0;
};

template <typename BlockAccessFn>
unsigned BufferBlockAccessor::accessTxBlock(const BlockAccessFn & fn, unsigned framesToTransfer)
{
    if (mTxChannels.mNumChannels == 0)
        throw std::invalid_argument("No TX channels configured");

    std::vector<int32_t *> ptrs(mTxChannels.mNumChannels, nullptr);
    framesToTransfer = clampTxFramesToTransfer(framesToTransfer);

    unsigned transferred = 0;
    while (transferred < framesToTransfer)
    {
        unsigned now = framesToTransfer - transferred;
        if (mClientTxHead + now > mBufferView.getBufferSizeFrames())
            now = mBufferView.getBufferSizeFrames() - mClientTxHead;

        for (unsigned ch = 0; ch < mTxChannels.mNumChannels; ++ch)
        {
            const auto & buf = mBufferView.getTxBufferDescription(mTxChannels.mFirstChannel + ch);
            ptrs[ch] = reinterpret_cast<int32_t *>(buf.sampleAt(mClientTxHead));
        }
        unsigned done     = fn(now, ptrs);
        mClientTxHead     = mBufferView.progressHead(mClientTxHead, done);
        mTxFramesToWrite -= static_cast<int>(done);
        transferred      += done;
        if (done == 0) break;
    }
    return transferred;
}

template <typename BlockAccessFn>
unsigned BufferBlockAccessor::accessRxBlock(const BlockAccessFn & fn, unsigned framesToTransfer)
{
    if (mRxChannels.mNumChannels == 0)
        throw std::invalid_argument("No RX channels configured");

    std::vector<int32_t *> ptrs(mRxChannels.mNumChannels, nullptr);
    if (framesToTransfer > mRxAvailable) framesToTransfer = mRxAvailable;

    unsigned transferred = 0;
    while (transferred < framesToTransfer && mRxAvailable > 0)
    {
        unsigned now = framesToTransfer - transferred;
        if (mClientRxHead + now > mBufferView.getBufferSizeFrames())
            now = mBufferView.getBufferSizeFrames() - mClientRxHead;

        for (unsigned ch = 0; ch < mRxChannels.mNumChannels; ++ch)
        {
            const auto & buf = mBufferView.getRxBufferDescription(mRxChannels.mFirstChannel + ch);
            ptrs[ch] = reinterpret_cast<int32_t *>(buf.sampleAt(mClientRxHead));
        }
        unsigned done  = fn(now, ptrs);
        mClientRxHead  = mBufferView.progressHead(mClientRxHead, done);
        mRxAvailable  -= done;
        transferred   += done;
        if (done == 0) break;
    }
    return transferred;
}

} // namespace Dante

// ==============================================================================
// DefaultBufferContext
// ==============================================================================

namespace Dante {

class DefaultBufferContext
{
public:
    struct WaitResult
    {
        BufferView::PollInfo pollInfo;
        std::vector<std::pair<BufferBlockAccessor *, int>> accessorLateValues;
        bool hasErrors() const { return !accessorLateValues.empty(); }
    };

    // ddhiTelemetry parameter accepted but ignored — DDHI not used in this build
    DefaultBufferContext(int inactiveTimeoutMs = -1, bool ddhiTelemetry = true);

    DefaultBufferContext(std::shared_ptr<IDanteLogger> log,
                         int  inactiveTimeoutMs = -1,
                         bool ddhiTelemetry     = true);

    ~DefaultBufferContext() = default;

    int connect(const std::string & shmName, bool globalNamespace, int timeoutSecs);

    bool isConnected() const { return mBuffers.isConnected(); }

    BufferView::PollInfo disconnect();
    WaitResult           wait();
    BufferView &         getBufferView() { return mBufferView; }

    void registerBlockAccessor(BufferBlockAccessor * acc)
        { mBlockAccessors.push_back(acc); }

    void deregisterBlockAccessor(BufferBlockAccessor * acc)
    {
        mBlockAccessors.erase(
            std::remove(mBlockAccessors.begin(), mBlockAccessors.end(), acc),
            mBlockAccessors.end());
    }

private:
    int connect(std::function<int()> connectFn, int timeoutSecs);

    Dante::Buffers             mBuffers;
    Dante::DanteBuffersAdapter mBufferAdapter;
    Dante::Timing              mTiming;

    std::shared_ptr<IDanteLogger>      mLog;
    BufferView                         mBufferView;
    std::vector<BufferBlockAccessor *> mBlockAccessors;

    int                                   mInactiveTimeoutMs;
    std::chrono::steady_clock::time_point mLastActiveTime;
};

} // namespace Dante
