//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
//
// 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
//		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
//		Software, provided always that the following conditions are met:
//		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
//				or be used in a product, solution or offering which requires the use of another licensed Audinate
//				product, solution or offering. The Software is not for use as a standalone product without any
//				reference to Audinate's products;
//		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
//				or expectation of performance, compatibility, support, updates or security; and
//		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
//				of the Software, and all derivative works of the Software, unless the copies or derivative works are
//				solely in the form of machine-executable object code generated by the source language processor.
//
// 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//		PURPOSE AND NONINFRINGEMENT.
//
// 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
//		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
//		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
//		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
//		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
//		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
//		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
//		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
//
// 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
//		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
//		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
//		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
//		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
//		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
//		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
//		4.2.	THE REPAIR OF THE SOFTWARE;
//		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
//				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
//
// 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
//		the trade names, or product names of Audinate.
//
// 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
//		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
//		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
//		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
//		liability.
//
// Log.hpp
// Log interface used in buffer access classes
//

#pragma once

#include <algorithm>
#include <chrono>
#include <cstdarg>
#include <cstdio>
#include <ctime>
#include <string>

#if defined(__GNUC__) || defined(__clang__)
#define DANTE_PRINTF_LIKE(fmt_index, first_arg) __attribute__((format(printf, fmt_index, first_arg)))
#else
#define DANTE_PRINTF_LIKE(fmt_index, first_arg)
#endif

namespace Dante {

enum class LogLevel
{
	NONE = 0,
	ERROR,
	WARNING,
	INFO,
	DEBUG
};

inline std::string toString(LogLevel level)
{
	switch (level)
	{
	case LogLevel::NONE:
		return "None";
	case LogLevel::ERROR:
		return "Error";
	case LogLevel::WARNING:
		return "Warning";
	case LogLevel::INFO:
		return "Info";
	case LogLevel::DEBUG:
		return "Debug";
	default:
		return "Unknown";
	}
}

inline LogLevel fromString(const std::string & str)
{
	std::string upperStr = str;
	std::transform(upperStr.begin(), upperStr.end(), upperStr.begin(), ::toupper);
	if (upperStr == "NONE")
	{
		return LogLevel::NONE;
	}
	else if (upperStr == "ERROR")
	{
		return LogLevel::ERROR;
	}
	else if (upperStr == "WARNING")
	{
		return LogLevel::WARNING;
	}
	else if (upperStr == "INFO")
	{
		return LogLevel::INFO;
	}
	else if (upperStr == "DEBUG")
	{
		return LogLevel::DEBUG;
	}
	else
	{
		return LogLevel::NONE;
	}
}

class IDanteLogger
{
public:
	virtual ~IDanteLogger() = default;

	/// Log a message with the given level using a printf-style format string
	/// and arbitrary additional arguments.
	virtual void log(LogLevel level, const char * format, ...) DANTE_PRINTF_LIKE(3, 4) = 0;
};

class PrintfLogger : public IDanteLogger
{
public:
	PrintfLogger(LogLevel threshold)
		: mThreshold(threshold)
	{}
	virtual ~PrintfLogger() = default;

	void log(LogLevel level, const char * format, ...) override DANTE_PRINTF_LIKE(3, 4)
	{
		if (level > mThreshold)
		{
			return;
		}

		// Prepend a timestamp and the log level to the log message
		char timeBuffer[32];
		auto now = std::chrono::system_clock::now();
		std::time_t now_c = std::chrono::system_clock::to_time_t(now);
		std::tm tmNow = *std::localtime(&now_c);

		char prefixedFormat[512];
		if (std::strftime(timeBuffer, sizeof(timeBuffer), "%Y-%m-%d %H:%M:%S", &tmNow) != 0)
		{
			std::snprintf(
				prefixedFormat,
				sizeof(prefixedFormat),
				"[%s] %s: %s\n",
				timeBuffer,
				toString(level).c_str(),
				format);
		}
		va_list args;
		va_start(args, format);
		std::vprintf(prefixedFormat, args);
		va_end(args);
	}

private:
	LogLevel mThreshold;
};

} // namespace Dante
//
// Copyright © 2026 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
//
